### ISSUE TITLE
Обговорення ночівлі

### ISSUE THREAD

**Issue by boyfromforest** [NastyaNaumuk/-#2]
Друзі, треба обговорити **місце ночівлі**.

Варіанти:
1. Верхнє Синьовидне(_готель_).
2. На березі річки Стрий(_у палатці_).
3. Поблизу гори Парашка(_у палатці_).

_На всякий випадок, в **Couchsurfing** я найду місцевого жителя, який міг би нас прийняти. Це буде безкоштовно!_

**Comment by boyfromforest** [comment]
До речі, у мене є трьохмісна палатка. 
Якщо вам підійде така ідея, то палатка вже є.

**Comment by NazarLipkovskij** [comment]
Так, мені підходить.

**Comment by NazarLipkovskij** [comment]
Крім того, я міг би взяти в свого друга ще одну палатку. Більше місця - більше комфорту.

**Comment by NastyaNaumuk** [comment]
Палатка це гарний варіант, + заощадить витрати.

**Comment by boyfromforest** [comment]
@Tania-Kusiak ти за такий варіант, як ночівля в палатці?

**Comment by Tania-Kusiak** [comment]
Так, я за палатку. спати на свіжому повітрі класно)

**Comment by boyfromforest** [comment]
**Поставте _лайки_ на цей коментар, якщо хочете ночувати поблизу гори Парашка.
_Серцечко_, якщо на березі річки Стрий.**

**Comment by boyfromforest** [comment]
**Вирішено!**
Обрано _Варіант №2._
