### ISSUE TITLE
Поділ речей в сумках

### ISSUE THREAD

**Issue by boyfromforest** [NastyaNaumuk/-#5]
**Народ, треба вирішити, хто які речі буде носити в своїх рюкзаках.**

**_Я б міг взяти засоби для проживання, електроніку всю та воду._** 

Що ви будете брати?

**Comment by NastyaNaumuk** [comment]
гроші))))

**Comment by Tania-Kusiak** [comment]
вода

**Comment by Tania-Kusiak** [comment]
палатка

**Comment by boyfromforest** [comment]
@NazarLipkovskij **тобі б здалось взяти другий намет, не будуть ж дівчата нести...**

**Comment by Tania-Kusiak** [comment]
медичні засоби та перекус в дорогу

**Comment by NazarLipkovskij** [comment]
Звісно возьму

**Comment by Tania-Kusiak** [comment]
@NastyaNaumuk ми могли б їжу взяти на половину

**Comment by NazarLipkovskij** [comment]
І я возьму половину їжі

**Comment by boyfromforest** [comment]
**Окей, вирішили, хто що буде нести.
Не забудьте взяти всі речі, бо потім буде бідаааааа....**
