### ISSUE TITLE
Хто буде фотографувати?

### ISSUE THREAD

**Issue by NazarLipkovskij** [NastyaNaumuk/-#6]

**Comment by NastyaNaumuk** [comment]
я , візьму з собою фотоапарат ))

**Comment by boyfromforest** [comment]
**Пропоную те, щоб я фотографував.
Бо я не фотогенічний, ну і добре фотографую.**

**Comment by boyfromforest** [comment]
**Якщо ви не проти:)**

**Comment by Tania-Kusiak** [comment]
я не проти
