### ISSUE TITLE
Оберіть спосіб, як доїхати до Карпат.

### ISSUE THREAD

**Issue by boyfromforest** [NastyaNaumuk/-#7]
**- [ ] Варіанти:**

- [x] Поїздом
- [ ] BlaBlaCar
- [x] Автобусом
- [ ] Велосипедами

Ну ще, на всякий випадок, можна добратись автостопом. Але це такий, запасний варіант!

**Comment by boyfromforest** [comment]
**Окей, я побачив за що більшість, тоді:**
` Поїздом чи автобус?`

**Comment by Tania-Kusiak** [comment]
автобусом

**Comment by NazarLipkovskij** [comment]
Давай поїзд. Він і швидший і зручніший.

**Comment by NastyaNaumuk** [comment]
я теж за поїзд!

**Comment by boyfromforest** [comment]
> Давай поїзд. Він і швидший і зручніший.

> я теж за поїзд!

**Я теж за поїзд.**

**Comment by boyfromforest** [comment]
Вирішено! Їдемо поїздом.
